disabled_rules: # rule identifiers to exclude from running
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - todo
  - type_body_length
  - line_length
  - syntactic_sugar
  - trailing_whitespace
  - colon
  - verticle_whitespaces
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - EclipseSoundscapes
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:

  min_length: # not possible to disable this partial rule, so set it to zero
    warning: 0
    error: 0
  excluded: # excluded via string array
    - id
    - CitizenScientistsDirectory
    - LocationDirectory
    - AllRecordings
    - QueueMin
    - QueueMax
    - Radius
    - RecordingDurationMin
    - RecordingDurationMax
    - FileType
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)